### ISSUE TITLE
Has no method buildHTML

### ISSUE THREAD

**Issue by firminochangani** [Stanko/rocketScroll#1]
I'm trying to use the rocketScroll in a extension of Google Chrome 30 and it return this error in console:  Uncaught TypeError: Object #<Object> has no method 'buildHTML'. I check your demo and i saw an other script "rocketHelper.js" for this reason i add it on the page with the library and the error just continue there.

PS: Sorry for my bad english, isn't my native language.

**Comment by Stanko** [comment]
Woah mate, sorry, I didn't see this comment till now. I planned to rewrite few things on this, so just let me know if you are still using it, and did you solved your problem?

**Comment by firminochangani** [comment]
@Stanko i'm not using anymore.

**Comment by Stanko** [comment]
Thank you for the response, I'll try to fix it anyway. Thanks!

**Comment by r3wt** [comment]
@Stanko the issue occurred for me while writing a directive to use this in angular. it was because i was passing an angular element instead of a raw element. the likely issue here is an invalid element. once i passed a raw dom node, all was well.

**Comment by Stanko** [comment]
As for angular this seems to help

http://stackoverflow.com/questions/18302493/is-there-a-way-to-get-the-raw-dom-element-from-an-angular-element

```
var angular_wrapped_element = angular.element(element);
var native_dom_element = angular_wrapped_element[0];
```

So probably, in the directive you can pass it like that.

**Comment by r3wt** [comment]
@Stanko see my other thread lol
